apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mindforge.fullname" . }}-config
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.configmap.data.SPRING_PROFILES_ACTIVE }}"
  DATABASE_URL: "{{ .Values.configmap.data.DATABASE_URL }}"