{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mindforge.fullname" . }}
spec:
  rules:
  - host: mindforge.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "mindforge.fullname" . }}
            port:
              number: 8080
{{- end }}