spring:
  application:
    name: mindforge
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: always

jwt:
  secret: verylongrandomstringwithatleast32chars!!!
  expiration: 3600000

frontend:
  url: http://localhost:3000

server:
  port: 8080
