spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mindforge
    username: devuser
    password: devpass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

jwt:
  secret: verylongrandomstringwithatleast32chars!!!
  expiration: 3600000
